# Generated by Django 5.1.5 on 2025-01-29 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_footballplayers_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.footballplayers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(related_name='teams', to='app.footballplayers')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_name', models.CharField(max_length=100)),
                ('win_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trophy', to='app.footballplayers')),
            ],
        ),
    ]
